version: '3.7'
services:
  dev:
    build: .
    tty: true
    stdin_open: true
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    ports:
      - 3000:3000

volumes:
  node_modules:
